### ISSUE TITLE
Cannot remove Node app

### ISSUE THREAD

**Issue by diabelb** [stefanpejcic/OpenPanel#567]
### OpenPanel version(s) affected

1.4.9

### Description

Removing node app does not work at all.

### Are you able to reproduce the problem on the demo site https://demo.openpanel.org:2083/ ?

Yes

### How to reproduce

Go to https://demo.openpanel.org:2083/sites -> Manage node app -> Remove -> Delete Application

**Comment by stefanpejcic** [comment]
Hello,

This was just implemented yesterday in 1.4.9  - can you check if you are indeed using the latest version? `opencli version`

- Is this an existing NodeJS app or newly-created now in 1.4.9?
- Which webserver is the user using?
- Is app configured on apex domain, subdomain or subdirectory?
- Do you get any error on delete in browser console or in openpanel error log?

-------

Can you append `&output=json` in the url, example: `https://demo.openpanel.org:2083/website?domain=%D0%BF%D0%B5%D1%82%D0%B0%D1%80.%D1%81%D1%80%D0%B1&output=json` and share just the 
 *container** and **pm2_data** parts:

```
{
  "container": {
    "admin_email": null,
    "created_date": "Fri, 11 Jul 2025 09:22:39 GMT",
    "domain_id": 3,
    "id": 5,
    "path": "/var/www/html/proba.srb",
    "port": "proba",
    "site_name": "петар.срб",
    "type": "nodejs",
    "version": "22.17.0"
  },


....


  "pm2_data": {
    "PROBA_NODE_CPU": "0.54",
    "PROBA_NODE_RAM": "0.8G",
    "PROBA_NODE_REQUIREMENTS": "1",
    "PROBA_NODE_STARTUP_FILE": "/var/www/html/app.js",
    "PROBA_NODE_TAG": "22.17.0",
    "PROBA_NODE_WORKDIR": "/var/www/html/petar.srb",
    "prefix": "PROBA_NODE_",
    "status": false
  },

```

**Comment by diabelb** [comment]
1. version 1.4.9 upgraded from 1.4.8, fresh install few days ago, not used
2. Default Nginx + varnish cache
3.  Apex domain, subdirectory - no difference
4. No error in browser, there is 500 error:

`MY_IP - - [15/Jul/2025:14:58:39 +0200] "POST /pm2/delete/jollywick.com HTTP/1.1" 500 89545 "https://HOST:2083/website?domain=jollywick.com" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36"
`

`"container":{"admin_email":null,"created_date":"Tue, 15 Jul 2025 12:50:03 GMT","domain_id":10,"id":4,"path":"/var/www/html/","port":"TEST1112","site_name":"jollywick.com","type":"NodeJS","version":"24.4.0"}`

`"pm2_data":{"TEST1112_NODE_CPU":"0.25","TEST1112_NODE_RAM":"0.25G","TEST1112_NODE_REQUIREMENTS":"1","TEST1112_NODE_STARTUP_FILE":"/var/www/html/","TEST1112_NODE_TAG":"24.4.0","TEST1112_NODE_WORKDIR":"/var/www/html/jollywick.com","prefix":"TEST1112_NODE_","status":false},"title":"jollywick.com","type":"nodejs"}`

**Comment by stefanpejcic** [comment]
thank you for the detailed information. I was able to reproduce the issue, and the root cause is that the application's status is inactive at the time of removal. This is visible in the provided output: `"status": false`.

As a result, Nginx fails to resolve the upstream and throws the following error:

```
2025/07/15 14:19:06 [emerg] 1#1: host not found in upstream "idemo" in /etc/nginx/conf.d/nesto.rs.conf:18
```

This causes Nginx to restart, and during the application's removal process, we're unable to validate the vhost file since Nginx is mid-restart.

When submitting the deletion, the following error appears in the logs (`docker logs -f openpanel`):

```
[2025-07-15 13:22:13,597] ERROR in app: Exception on /pm2/delete/nesto.rs/idemo [POST]
Traceback (most recent call last):
  ...
Exception: Failed to read file: Error response from daemon: Container 7345f0821fe3... is restarting, wait until the container is running

ERROR:root:Error Code: tuhvMVIbAUIls376KlQlCqVf - 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

---

temporary workaround:

- update opencli with: `cd /usr/local/opencli && git pull`
- add a new domain for the user  (this revalidates Nginx and brings it back up),
- start the application for that user,
- then remove the desired app.

---

For update i'll edit it to skip nginx config verification during delete, and perform it on host os not contianer, so it will work even if nginx is not running.

Thanks again for reporting this!

**Comment by diabelb** [comment]
Wow. Fastest bug fixing i've ever seen  ;D. Stay tuned. I have few more. 👍

**Comment by stefanpejcic** [comment]
this should be resolved in upcoming version 1.5.1 - the webserver no longer needs to be active to remove the reverse proxy, and we no longer check status after reload.

**Comment by diabelb** [comment]
After updating to 1.5.1 this bug still exists. I cannot remove empty node app.
